# Generated by Django 4.2.16 on 2024-10-28 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WxAppUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nick_name", models.CharField(default="", max_length=255)),
                ("gender", models.IntegerField(default=0)),
                ("city", models.CharField(default="", max_length=100)),
                ("province", models.CharField(default="", max_length=100)),
                ("country", models.CharField(default="", max_length=100)),
                ("avatarUrl", models.CharField(default="", max_length=500)),
                ("unionId", models.CharField(default="", max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wxapp_user_profile",
                "ordering": ["-created"],
            },
        ),
    ]
