services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 casher.asgi:application
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"  # 将 Nginx 的 8000 端口暴露给 Nomad
    volumes:
      - ./web:/usr/share/nginx/html/web
      - ./web-b:/usr/share/nginx/html/web-b
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
