services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 casher.asgi:application
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx-ssl:
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - ./web:/usr/share/nginx/html/web
      - ./web-b:/usr/share/nginx/html/web-b
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
      - aidep.cn.key:/etc/nginx
      - aidep.cn_bundle.crt:/etc/nginx
    depends_on:
      - web
