services:
  web:
    build: .
#    command: daphne -b 0.0.0.0 -p 8000 casher.asgi:application
    command: python manage.py runserver
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./web:/usr/share/nginx/html/web
      - ./web-b:/usr/share/nginx/html/web-b
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
      - ../aidep.cn_bundle.crt:/etc/nginx/aidep.cn_bundle.crt
      - ../aidep.cn.key:/etc/nginx/aidep.cn.key
    depends_on:
      - web

networks:
  mynetwork:
    driver: bridge
