# Generated by Django 4.2.16 on 2024-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wxappb", "0003_rename_wxappbtechs_authortechs"),
    ]

    operations = [
        migrations.AddField(
            model_name="authortechs",
            name="unionid",
            field=models.CharField(default="", max_length=100),
        ),
    ]
