# Generated by Django 4.2.16 on 2024-10-29 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WechatOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_trade_no", models.CharField(max_length=100)),
                ("prepay_id", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("desc", models.TextField(default="")),
                ("pay_type", models.IntegerField()),
                ("status", models.CharField(default="prepay", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wechat_order",
            },
        ),
        migrations.CreateModel(
            name="UserHashrate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashrate", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_hashrate",
            },
        ),
        migrations.CreateModel(
            name="StripePaymentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_profile",
            },
        ),
        migrations.CreateModel(
            name="PagsmilePayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("phone", models.CharField(default="", max_length=20)),
                ("email", models.CharField(default="", max_length=20)),
                ("account", models.CharField(default="", max_length=20)),
                ("account_type", models.CharField(default="", max_length=20)),
                ("method", models.CharField(default="WALLET", max_length=20)),
                ("channel", models.CharField(default="PayPal", max_length=20)),
                ("custom_code", models.CharField(max_length=20)),
                ("fee_bear", models.CharField(default="merchant", max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("source_currency", models.CharField(default="USD", max_length=20)),
                ("arrival_currency", models.CharField(default="USD", max_length=20)),
                (
                    "notify_url",
                    models.CharField(
                        default="http://aidep.cn/payment/pagsmile/callback/",
                        max_length=20,
                    ),
                ),
                ("additional_remark", models.TextField(default="")),
                ("country", models.CharField(default="USA", max_length=20)),
                ("status", models.CharField(default="prepayout", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pagsmile_payout",
                "indexes": [
                    models.Index(fields=["custom_code"], name="custom_code_idx")
                ],
            },
        ),
    ]
