# Generated by Django 4.2.16 on 2024-11-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_take", models.FloatField(default=0.7)),
                ("invitation_take", models.FloatField(default=0.1)),
                ("platform_take", models.FloatField(default=0.2)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commission_config",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="CashStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashable",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "withdrawing",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "withdrawned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "in_transit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "refunded",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cash_statistics",
                "ordering": ["-updated"],
            },
        ),
    ]
