# Generated by Django 4.2.16 on 2024-10-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("image", models.ImageField(upload_to=task.models.upload_cs_image_to)),
                ("subfolder", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jilu_id", models.CharField(max_length=100)),
                ("fee", models.IntegerField(default=10)),
                ("prompt_id", models.CharField(default="", max_length=50)),
                ("prompt_text", models.TextField(default="")),
                ("status", models.CharField(default="queue", max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flow.workflowdata",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.userupload",
                    ),
                ),
            ],
            options={
                "db_table": "user_task",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.ImageField(upload_to=task.models.upload_cs_image_result),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.usertask"
                    ),
                ),
            ],
            options={
                "db_table": "task_result",
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="usertask",
            index=models.Index(fields=["prompt_id"], name="prompt_id_idx"),
        ),
        migrations.AddIndex(
            model_name="usertask",
            index=models.Index(fields=["jilu_id"], name="jilu_id_idx"),
        ),
    ]
