# Generated by Django 4.2.16 on 2024-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkFlowBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("desc", models.TextField()),
                ("en_desc", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_banner",
                "ordering": ["-created"],
            },
        ),
    ]
