# Generated by Django 4.2.16 on 2024-11-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0003_rename_en_desc_workflowbanner_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowdata",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowdata",
            name="status",
            field=models.CharField(default="online", max_length=10),
        ),
    ]
