# Generated by Django 4.2.16 on 2024-11-14 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_workflowdata_deleted_workflowdata_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowbanner",
            name="workflow",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="flow.workflowdata",
            ),
            preserve_default=False,
        ),
    ]
