# Generated by Django 4.2.16 on 2024-11-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_workflowbanner_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkFlowCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("task_count", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counts",
                        to="flow.workflowdata",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_count",
                "ordering": ["-created"],
            },
        ),
    ]
