# Generated by Django 4.2.16 on 2024-11-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_workflowcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowbanner",
            name="en_desc",
            field=models.TextField(default=""),
        ),
    ]
